services:
  app:
    build: .
    container_name: php_app
    volumes:
      - ./src:/var/www/html
    ports:
      - 8000:80
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: blog
      MYSQL_USER: admin
      MYSQL_PASSWORD: 123
    ports:
      - 3306:3306
    volumes:
      - db_data:/var/lib/mysql
      - ./docker/mysql/initdb:/docker-entrypoint-initdb.d

volumes:
  db_data:
