CREATE DATABASE IF NOT EXISTS blog CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE blog;

CREATE TABLE IF NOT EXISTS usuarios (
  id INT AUTO_INCREMENT PRIMARY KEY,
  nome VARCHAR(100) NOT NULL,
  email VARCHAR(100) NOT NULL UNIQUE,
  senha VARCHAR(255) NOT NULL,
  admin BOOLEAN NOT NULL DEFAULT 0
);

INSERT INTO usuarios (nome, email, senha, admin)
VALUES ('Administrador', 'admin@teste.com', '$2y$10$6kDAY1.akeVJYC1ud1IIPOZMS5q58qAPvBkGikcetWodzxBdo2v0G', 1);

CREATE TABLE IF NOT EXISTS postagens (
  id INT AUTO_INCREMENT PRIMARY KEY,
  titulo VARCHAR(45) NOT NULL,
  conteudo TEXT NOT NULL,
  usuario_id INT NOT NULL,
  criado_em DATETIME DEFAULT CURRENT_TIMESTAMP,
  editado_em DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY (usuario_id) REFERENCES usuarios(id) ON DELETE CASCADE
);
